# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "laravel/homestead"

  # config.vm.box_check_update = false

  #config.vm.network "forwarded_port", guest: 80, host: 80
  #config.vm.network "forwarded_port", guest: 3306, host: 3306
  
  config.vm.network "private_network", ip: "10.10.10.25"
  # config.vm.network "public_network"

  config.vm.synced_folder "./..", "/home/vagrant/restaurant-test"

  config.vm.provider "virtualbox" do |vb|
	vb.customize ["modifyvm", :id, "--memory", 1024]
    vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/vagrant", "1"]
  end
  
  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

  # config.vm.provision "setup", type: "shell", path: "setup.sh"
  # config.vm.provision "run", type: "shell", path: "run.sh", run: "always"
end
